---

#disabled hostkeychecking for ansible with password connection
ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'


#root public network
__root_public_network: "172.18.1"

#root private network
__root_private_network: "172.19.2"


